### ISSUE TITLE
Add to words.json file

### ISSUE THREAD

**Issue by DoubleNemesis** [DoubleNemesis/rhyme-grab#1]
More data is needed for this game. I need additions to the `data/words.json` file. Please read the contributing.md doc for full details. More than one person can contribute but please reply to this issue if you are interested and I will give you the go-ahead.

**Comment by priyanshu688** [comment]
@DoubleNemesis I can work on this issue if you will brief me what exactly I need to do

**Comment by DoubleNemesis** [comment]
Hi @priyanshu688 
it's basically creating some JSON data with words I'm using to make a game. There's a long explanation in the contributing.md doc. Let me know if there's anything in there that doesn't make sense to you!
Cheers

**Comment by Shivansh-yadav13** [comment]
Can I add some words? @DoubleNemesis  :)

**Comment by DoubleNemesis** [comment]
@Shivansh-yadav13 yes,  go for it!

**Comment by Geraldlyon** [comment]
Hi @DoubleNemesis,
I will love to contribute to words.json✔

**Comment by DoubleNemesis** [comment]
@Geraldlyon Great! Go for it! All the info is in the contributing.md!

**Comment by Geraldlyon** [comment]
great👍
